version: '3.8'

services:
  app:
    build: .
    container_name: start_up
    restart: always
    ports:
      - '4002:4002'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: start_up-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: O9M1a8r5+=2004
      POSTGRES_DB: start_up
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: start_up-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
